CREATE TABLE shop (
id INT NOT NULL AUTO_INCREMENT,
user_id INT NOT NULL UNIQUE,
name VARCHAR(64) NOT NULL UNIQUE,
display_name VARCHAR(256) NOT NULL,
description VARCHAR(512),
bulletin VARCHAR(512),
VERIFIED INT default 0,
label VARCHAR(512),
offer_labels VARCHAR(512),
blog_labels VARCHAR(512),
country varchar(128),
city varchar(128),
address varchar(256),
zip varchar(20),
longitude INT(11),
latitude INT(11),
update_time DATETIME,
logo_url varchar(512),
banner_url varchar(512),
telephone varchar(64),
offer_num INT NOT NULL default 0,
blog_num INT NOT NULL default 0,
visit_num INT NOT NULL default 0,
comment_num INT NOT NULL default 0,
PRIMARY KEY (id),
FOREIGN KEY (user_id) REFERENCES user(id) on delete cascade 
) ENGINE=InnoDB default charset=utf8;