CREATE TABLE weibo_user (
id 			INT NOT NULL AUTO_INCREMENT,
weibo_user_id 		varchar(256),
screen_name 		varchar(256),
name 			varchar(256),
province 		INT default 0,
city 			INT default 0,
location 		varchar(256),
description 		varchar(1024),
url			varchar(256),
profile_image_url	varchar(256),
gender			varchar(256),
followers_count		INT default 0,
friends_count		INT default 0,
statuses_count		INT default 0,
favourites_count	INT default 0,
created_at		DATETIME,	
verified		INT default 0,
verified_type		INT default 0,
avatar_large		varchar(256),
bifollower_count	INT default 0,
lang			varchar(256),
PRIMARY KEY (id)
) ENGINE=InnoDB default charset=utf8;
